# Generated by Django 3.2.9 on 2022-07-09 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorter_history',
            name='short_url',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
